book/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.shortcuts import render
from django.template import Template
app_name = 'book'
urlpatterns = [
    # path('book',views.index)
    # path('book/<book_id>', views.index1),
    # path('book/<int:book_id>', views.index1)
    path('list', views.list,name='book_list'),
    # path('list/<str:list_id>', views.list),
    path('details', views.details,name='book_details'),
    path('book_to',views.book_list_to_movie_list,name= 'book_to'),
    path('test', views.test,name='test'),
]

djangoa/urls.py
import requests
from django.contrib import admin
from django.shortcuts import render
from django.urls import path,include
from book import views
from django.http import HttpResponse
from django.template import Template

def index(request):
    # 项目列表
    # projects = ['项目1','项目2']  # 获取所有项目
    url = "http://localhost:5000/project/project_list"  # 确保这与运行Flask应用的地址和端口匹配
    response = requests.get(url)
    projects=response.json()
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'project_list.html', context)  # 渲染模板并返回响应

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('book/',include('book.urls'),name='book'),
    path('movie/',include('movie.urls'),name='movie'),
    path('project/',include('project.urls'),name='project'),
    path('environment/',include('environment.urls'),name='environment'),
    path('tplans/',include('tplans.urls'),name='tplans'),
    path('interfaces/',include('interfaces.urls'),name='interfaces'),
    path('cases/',include('cases.urls'),name='cases'),
    path('processes/',include('processes.urls'),name='processes'),
    path('tasks/',include('tasks.urls'),name='tasks'),
    path('reports/',include('reports.urls'),name='reports'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# 给app命名
app_name='project'
# 映射html
urlpatterns = [
    path('list', views.list,name='project_list'),
    path('add', views.add,name='project_add'),
    path('details', views.details_list,name='project_details_list'),
    path('delete', views.delete,name='project_delete'),
    # path('add', views.delete,name='project_delete'),
]

tasks/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.shortcuts import render
from django.template import Template
app_name = 'tasks'#定时任务
urlpatterns = [
    # path('book',views.index)
    # path('book/<book_id>', views.index1),
    # path('book/<int:book_id>', views.index1)
    path('list', views.list,name='list'),
    path('delete', views.delete, name='delete'),
    path('details', views.details, name='details'),
    path('content/details', views.content_details, name='content_details'),
    path('content/delete', views.content_delete, name='content_delete'),

]

tasks/models.py
from django.db import models

# Create your models here.

tasks/views.py
from django.shortcuts import render

# Create your views here.
def list(request):
    #定时任务列表
    projects = {'定时任务1', '定时任务2'}  # 获取所有项目
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'tasks_list.html', context)  # 渲染模板并返回响应

def delete(request):
    #删除定时任务
    pass
    return render(request, 'tasks_delete.html', )  # 渲染模板并返回响应

def details(request):
    #定时任务详情,也是定时任务内容列表
    pass
    projects = {'定时任务内容1', '定时任务内容2'}  # 获取所有项目
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'tasks_details.html', context)  # 渲染模板并返回响应

def content_details(request):
    #定时任务内容
    pass
    return render(request, 'tasks_details_content.html', )  # 渲染模板并返回响应

def content_delete(request):
    #定时任务内容删除
    pass
    return render(request, 'tasks_details_content_delete.html', )  # 渲染模板并返回响应

tasks/templates/tasks_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>定时任务删除成功</title>
</head>
<body>
    <div >
        <a href="{% url 'tasks:list' %}">返回上一页</a>
        <h1>定时任务删除成功</h1>
    </div>
</body>
</html>

tasks/templates/tasks_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>定时任务列表</title>
</head>
<body>
    <div >
        <a href="{% url 'tasks:list' %}">返回上一页</a>
        <h1>定时任务列表</h1>
        {% for project in projects %}
            <div class="project">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
                <a href="{% url 'tasks:content_details' %}">定时任务详情</a>
                <a href="{% url 'tasks:content_delete' %}">定时任务删除</a>
            </div>
        {% endfor %}
    </div>
</body>
</html>

tasks/templates/tasks_details_content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>定时任务内容详情</title>
</head>
<body>
    <div >
        <a href="{% url 'tasks:details' %}">返回上一页</a>
        <h1>定时任务内容详情</h1>
    </div>
</body>
</html>

tasks/templates/tasks_details_content_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>定时任务内容删除成功</title>
</head>
<body>
    <div >
        <a href="{% url 'tasks:details' %}">返回上一页</a>
        <h1>定时任务内容删除成功</h1>
    </div>
</body>
</html>

tasks/templates/tasks_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>定时任务1</title>
</head>
<body>
    <div >
        <a href="{% url 'project:project_details_list' %}">返回上一页</a>
        <h1>定时任务1</h1>
        {% for project in projects %}
            <div class="project">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
                <a href="{% url 'tasks:details' %}">定时任务1详情</a>
                <a href="{% url 'tasks:delete' %}">定时任务1删除</a>
            </div>
        {% endfor %}
    </div>
</body>
</html>