book/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.shortcuts import render
from django.template import Template
app_name = 'book'
urlpatterns = [
    # path('book',views.index)
    # path('book/<book_id>', views.index1),
    # path('book/<int:book_id>', views.index1)
    path('list', views.list,name='book_list'),
    # path('list/<str:list_id>', views.list),
    path('details', views.details,name='book_details'),
    path('book_to',views.book_list_to_movie_list,name= 'book_to'),
    path('test', views.test,name='test'),
]

cases/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.shortcuts import render
from django.template import Template
app_name = 'cases'#接口用例
urlpatterns = [
    path('list', views.list,name='list'),
    path('interfaces', views.interfaces_list,name='interfaces'),
    path('details', views.details,name='details'),
    path('delete', views.delete,name='delete'),
    path('add', views.add,name='add'),
    path('update', views.update, name='update'),
]

djangoa/urls.py
import requests
from django.contrib import admin
from django.shortcuts import render
from django.urls import path,include
from book import views
from django.http import HttpResponse
from django.template import Template

def index(request):
    # 项目列表
    # projects = ['项目1','项目2']  # 获取所有项目
    url = "http://localhost:5000/project/project_list"  # 确保这与运行Flask应用的地址和端口匹配
    response = requests.get(url)
    projects=response.json()
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'project_list.html', context)  # 渲染模板并返回响应

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('book/',include('book.urls'),name='book'),
    path('movie/',include('movie.urls'),name='movie'),
    path('project/',include('project.urls'),name='project'),
    path('environment/',include('environment.urls'),name='environment'),
    path('tplans/',include('tplans.urls'),name='tplans'),
    path('interfaces/',include('interfaces.urls'),name='interfaces'),
    path('cases/',include('cases.urls'),name='cases'),
    path('processes/',include('processes.urls'),name='processes'),
    path('tasks/',include('tasks.urls'),name='tasks'),
    path('reports/',include('reports.urls'),name='reports'),
]

interfaces/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.shortcuts import render
from django.template import Template
app_name = 'interfaces'#接口管理
urlpatterns = [
    path('list', views.list,name='list'),
    path('details', views.details,name='details'),
    path('delete', views.delete,name='delete'),
    path('add', views.add,name='add'),
    path('update', views.update, name='update'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# 给app命名
app_name='project'
# 映射html
urlpatterns = [
    path('list', views.list,name='project_list'),
    path('add', views.add,name='project_add'),
    path('details', views.details_list,name='project_details_list'),
    path('delete', views.delete,name='project_delete'),
    # path('add', views.delete,name='project_delete'),
]

cases/models.py
from django.db import models

# Create your models here.

cases/views.py
import logging

import requests
from django.shortcuts import render

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Create your views here.
def interfaces_list(request):
    #接口列表
    if request.method == 'POST':
        project_name = request.POST.get('project_datails')

    url_all = "http://localhost:5000/intercase/intercase_list"
    # 准备要发送的JSON数据

    data_all = {
        "project_name": f"{project_name}"
    }

    logging.info(f'data_all:{data_all}')
    projects_all = requests.post(url_all, json=data_all)
    projects_json_all = projects_all.json()
    logging.info(f'projects_json_all:{projects_json_all}')


    projects2 = []
    projects2.append(project_name)


    context = {'projects2': projects2,'projects3':projects_json_all}  # 创建上下文数据
    return render(request, 'interfaces_update.html', context)  # 渲染模板并返回响应


    projects = {'接口1', '接口2'}  # 获取所有项目
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'cases_interfaces_list.html', context)  # 渲染模板并返回响应

def list(request):
    #接口用例列表
    if request.method == 'POST':
        project_name = request.POST.get('project_datails')

    url_all = "http://localhost:5000/intercase/intercase_list"
    # 准备要发送的JSON数据

    data_all = {
        "project_name": f"{project_name}"
    }

    logging.info(f'data_all:{data_all}')
    projects_all = requests.post(url_all, json=data_all)
    projects_json_all = projects_all.json()
    logging.info(f'projects_json_all:{projects_json_all}')

    cases_name_list = [entry[2] for entry in projects_json_all]
    logging.info(f"interface_name_list:{cases_name_list}")

    projects2 = []
    projects2.append(project_name)

    context = {'projects2': projects2,'cases_name_list':cases_name_list}  # 创建上下文数据
    return render(request, 'cases_list.html', context)  # 渲染模板并返回响应



def details(request):
    # 接口用例详情
    if request.method == 'POST':
        project_name = request.POST.get('project_datails')
        old_title = request.POST.get('old_title')
    url_all = "http://localhost:5000/intercase/intercase_details"
    # 准备要发送的JSON数据

    data_all = {
        "project_name": f"{project_name}",
        "old_title": f"{old_title}"

    }

    logging.info(f'data_all:{data_all}')
    projects_all = requests.post(url_all, json=data_all)
    projects_json_all = projects_all.json()
    logging.info(f'projects_json_all:{projects_json_all}')

    new_title = projects_json_all[0][2]
    interfaes_id = projects_json_all[0][3]
    headers = projects_json_all[0][4]
    case_request = projects_json_all[0][5]
    case_file = projects_json_all[0][6]
    case_setup_script = projects_json_all[0][7]
    case_teardown_script = projects_json_all[0][8]

    old_title_list=[]
    old_title_list.append(old_title)

    interfaes_id_list=[]
    interfaes_id_list.append(interfaes_id)

    headers_list=[]
    headers_list.append(headers)

    case_request_list=[]
    case_request_list.append(case_request)

    case_file_list=[]
    case_file_list.append(case_file)

    case_setup_script_list=[]
    case_setup_script_list.append(case_setup_script)

    case_teardown_script_list=[]
    case_teardown_script_list.append(case_teardown_script)

    projects2 = []
    projects2.append(project_name)

    context = {'projects2': projects2,'old_title_list':old_title_list,'interfaes_id_list':interfaes_id_list,
               'headers_list':headers_list,'case_request_list':case_request_list,'case_file_list':case_file_list,
               'case_setup_script_list':case_setup_script_list,'case_teardown_script_list':case_teardown_script_list}  # 创建上下文数据
    return render(request, 'cases_details.html', context)  # 渲染模板并返回响应

def update(request):
    if request.method == 'POST':
        project_name = request.POST.get('project_datails')
        old_title = request.POST.get('old_title')


    data = {
        "project_name": "自动化测试平台",
        'interface':2,
        "title": "1",
        "headers": {"Content-Type": "application/json"},
        "request": {"name": "1test项目新增"},
        "file": {"": ""},
        "setup_script": "",
        "teardown_script": "",
        "title": "2"
    }

    return render(request, 'cases_details.html')  # 渲染模板并返回响应




def delete(request):
    # 删除接口用例
    if request.method == 'POST':
        cases_name = request.POST.get('cases_name')
        project_name = request.POST.get('project_datails')

    url_all = "http://localhost:5000/intercase/intercase_delete"
    # 准备要发送的JSON数据

    data_all = {
        "title": f"{cases_name}"
    }

    logging.info(f'data_all:{data_all}')
    projects_all = requests.post(url_all, json=data_all)
    projects_json_all = projects_all.json()
    logging.info(f'projects_json_all:{projects_json_all}')

    projects2 = []
    projects2.append(project_name)

    context = {'projects2': projects2}  # 创建上下文数据
    return render(request, 'cases_delete.html', context)  # 渲染模板并返回响应

def add(request):
    # 新增接口用例
    if request.method == 'POST':
        project_name = request.POST.get('project_datails')
        cases_old_name = request.POST.get('caces_name')
    url_all = "http://localhost:5000/intercase/intercase_add"
    # 准备要发送的JSON数据

    data_all = {
        "project_name": f"{project_name}",
        'title':f'{cases_old_name}'
    }

    logging.info(f'data_all:{data_all}')
    projects_all = requests.post(url_all, json=data_all)
    projects_json_all = projects_all.json()
    logging.info(f'projects_json_all:{projects_json_all}')

    projects2 = []
    projects2.append(project_name)

    context = {'projects2': projects2}  # 创建上下文数据
    return render(request, 'cases_add.html', context)  # 渲染模板并返回响应

cases/templates/cases_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新增接口用例</title>
</head>
<body>
    <div>新增接口用例成功</div>
    {% for project_name in projects2 %}
    <div>
        <form action="{% url 'cases:list' %}" method="post" style="display:inline;"> <!-- 表单，提交查看并编辑环境的请求 -->
            {% csrf_token %} <!-- 添加CSRF令牌，防止跨站请求伪造 -->
            <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
            <button type="submit">返回上一页</button> <!-- 提交按钮，查看并编辑环境 -->
         </form>
    </div>
    {% endfor %}
</body>
</html>

cases/templates/cases_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>删除接口用例</title>
</head>
<body>
    <div>删除接口用例成功</div>
    {% for project_name in projects2 %}
    <div>
        <form action="{% url 'cases:list' %}" method="post" style="display:inline;"> <!-- 表单，提交查看并编辑环境的请求 -->
            {% csrf_token %} <!-- 添加CSRF令牌，防止跨站请求伪造 -->
            <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
            <button type="submit">返回上一页</button> <!-- 提交按钮，查看并编辑环境 -->
         </form>
    </div>
    {% endfor %}






</body>
</html>

cases/templates/cases_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>接口用例详情</title>
</head>
<body>
    {% for project_name in projects2 %}
        <div>
            <form action="{% url 'cases:list' %}" method="post" style="display:inline;"> <!-- 表单，提交查看并编辑环境的请求 -->
                {% csrf_token %} <!-- 添加CSRF令牌，防止跨站请求伪造 -->
                <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                <button type="submit">返回上一页</button> <!-- 提交按钮，查看并编辑环境 -->
             </form>
        </div>
    {% endfor %}

    <div>
        {% for old_title in old_title_list %}
            <form method="post" action="{% url 'cases:update' %}" style="display:inline;">
                {% csrf_token %}
                <h1>old_title: {{ old_title }}</h1>
                {% for interfaes_id in interfaes_id_list %}
                    {% csrf_token %}
                    <h1>
                        接口id：{{ interfaes_id }}
                    </h1>
                {% endfor %}

                {% for headers in headers_list %}
                    {% csrf_token %}
                    <h1>
                        接口用例请求头：{{ headers }}
                    </h1>
                {% endfor %}

                {% for case_request in case_request_list %}
                    {% csrf_token %}
                    <h1>
                        接口用例请求参数：{{ case_request }}
                    </h1>
                {% endfor %}

                {% for case_file in case_file_list %}
                    {% csrf_token %}
                    <h1>
                        接口用例请求参数：{{ case_file }}
                    </h1>
                {% endfor %}

                {% for case_setup_script in case_setup_script_list %}
                    {% csrf_token %}
                    <h1>
                        接口用例前置脚本：{{ case_setup_script }}
                    </h1>
                {% endfor %}

                {% for case_teardown_script in case_teardown_script_list %}
                    {% csrf_token %}
                    <h1>
                        接口用例后置脚本：{{ case_teardown_script }}
                    </h1>
                {% endfor %}




                接口用例名：
                <input type="text" name="new_title" style="width: 200px; margin-right: 10px;" placeholder="请输入接口用例名">
                接口id：
                <input type="text" name="interface_url" style="width: 200px; margin-right: 10px;" placeholder="接口id">
                接口用例请求头：
                <input type="text" name="headers" style="width: 200px; margin-right: 10px;" placeholder="0or1">
                接口用例请求参数：
                <input type="text" name="case_request" style="width: 200px; margin-right: 10px;">
                接口用例前置脚本：
                <input type="text" name="case_setup_script" style="width: 200px; margin-right: 10px;">
                接口用例后置脚本：
                <input type="text" name="case_teardown_script" style="width: 200px; margin-right: 10px;">

                <br /><br /><!--服务器域名输入且换行两次-->
                <input type="hidden" name="old_title" value="{{ old_title }}"> <!-- 隐藏输入框，传递接口老名称 -->
                <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                提交按钮   <input type="submit"/><!--提交以上输入内容-->
            </form>
        {% endfor %}

    </div>

</body>
</html>

cases/templates/cases_interfaces_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>接口用例列表</title>
</head>
<body>
 {% for project_name in projects2 %}
    <div class="container">
        <form action="{% url 'project:project_details_list' %}" method="post" style="display:inline;"> <!-- 表单，提交查看并编辑接口用例的请求 -->
            {% csrf_token %} <!-- 添加CSRF令牌，防止跨站请求伪造 -->
            <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
            <button type="submit">返回上一页</button> <!-- 提交按钮，查看并编辑接口用例 -->
         </form>

        <h1>{{ project_name }}-接口用例列表</h1>
        <form method="post" action="{% url 'interfaces:add' %}">
            {% csrf_token %}
            <input type="text" name="caces_name" style="width: 200px; margin-right: 10px;" placeholder="请输入接口用例名称">
            <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
            <button type="submit">新增接口用例</button>
        </form>

        {% for interface_name in projects %}
            <div class="project">
<!--                <h2>{{ interface_name.title }}</h2>-->
                <h2>{{ interface_name }}</h2>
                <form method="post" action="{% url 'interfaces:details' %}" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                    <input type="hidden" name="interface_old_name" value="{{ interface_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                    <button type="submit">接口用例详情</button>
                </form>
                <form method="post" action="{% url 'interfaces:delete' %}" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="interface_name" value="{{ interface_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                    <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                    <button type="submit">删除</button>
                </form>
            </div>
        {% endfor %}
    {% endfor %}
    </div>
</body>
</html>

cases/templates/cases_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>接口用例列表</title>
</head>
<body>
    {% for project_name in projects2 %}
    <div class="container">
        <form action="{% url 'project:project_details_list' %}" method="post" style="display:inline;"> <!-- 表单，提交查看并编辑接口用例的请求 -->
            {% csrf_token %} <!-- 添加CSRF令牌，防止跨站请求伪造 -->
            <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
            <button type="submit">返回上一页</button> <!-- 提交按钮，查看并编辑接口用例 -->
         </form>

        <h1>{{ project_name }}-接口用例列表</h1>
        <form method="post" action="{% url 'cases:add' %}">
            {% csrf_token %}
            <input type="text" name="caces_name" style="width: 200px; margin-right: 10px;" placeholder="请输入接口用例名称">
            <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
            <button type="submit">新增接口用例</button>
        </form>

        {% for cases_name in cases_name_list %}
            <div class="project">
<!--                <h2>{{ interface_name.title }}</h2>-->
                <h2>{{ cases_name }}</h2>
                <form method="post" action="{% url 'cases:details' %}" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                    <input type="hidden" name="old_title" value="{{ cases_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                    <button type="submit">接口用例详情</button>
                </form>
                <form method="post" action="{% url 'cases:delete' %}" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="cases_name" value="{{ cases_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                    <input type="hidden" name="project_datails" value="{{ project_name }}"> <!-- 隐藏输入框，传递项目名称 -->
                    <button type="submit">删除</button>
                </form>
            </div>
        {% endfor %}
    {% endfor %}
    </div>
</body>
</html>

cases/templates/cases_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>