book/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.shortcuts import render
from django.template import Template
app_name = 'book'
urlpatterns = [
    # path('book',views.index)
    # path('book/<book_id>', views.index1),
    # path('book/<int:book_id>', views.index1)
    path('list', views.list,name='book_list'),
    # path('list/<str:list_id>', views.list),
    path('details', views.details,name='book_details'),
    path('book_to',views.book_list_to_movie_list,name= 'book_to'),
    path('test', views.test,name='test'),
]

djangoa/urls.py
import requests
from django.contrib import admin
from django.shortcuts import render
from django.urls import path,include
from book import views
from django.http import HttpResponse
from django.template import Template

def index(request):
    # 项目列表
    # projects = ['项目1','项目2']  # 获取所有项目
    url = "http://localhost:5000/project/project_list"  # 确保这与运行Flask应用的地址和端口匹配
    response = requests.get(url)
    projects=response.json()
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'project_list.html', context)  # 渲染模板并返回响应

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('book/',include('book.urls'),name='book'),
    path('movie/',include('movie.urls'),name='movie'),
    path('project/',include('project.urls'),name='project'),
    path('environment/',include('environment.urls'),name='environment'),
    path('tplans/',include('tplans.urls'),name='tplans'),
    path('interfaces/',include('interfaces.urls'),name='interfaces'),
    path('cases/',include('cases.urls'),name='cases'),
    path('processes/',include('processes.urls'),name='processes'),
    path('tasks/',include('tasks.urls'),name='tasks'),
    path('reports/',include('reports.urls'),name='reports'),
]

processes/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.shortcuts import render
from django.template import Template
app_name = 'processes'#业务流程
urlpatterns = [
    path('flow/list', views.flow_list,name='flow_list'),
    path('flow/delete', views.flow_delete,name='flow_delete'),
    path('flow/details', views.flow_details,name='flow_details'),
    path('flow/details/addstep', views.addstep,name='addstep'),
    path('flow/details/deletestep', views.deletestep,name='deletestep'),
    path('flow/details/detailsstep', views.detailsstep,name='detailsstep'),
    # path('list', views.list,name='list'),

]

project/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# 给app命名
app_name='project'
# 映射html
urlpatterns = [
    path('list', views.list,name='project_list'),
    path('add', views.add,name='project_add'),
    path('details', views.details_list,name='project_details_list'),
    path('delete', views.delete,name='project_delete'),
    # path('add', views.delete,name='project_delete'),
]

processes/models.py
from django.db import models

# Create your models here.

processes/views.py
from django.shortcuts import render

# Create your views here.
def flow_list(request):
    # 业务流程flow列表
    projects = {'业务流程1', '业务流程2'}  # 获取所有项目
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'processes_flow_list.html', context)  # 渲染模板并返回响应

def flow_delete(request):
    # 业务流程删除
    pass
    return render(request, 'processes_delete.html',)  # 渲染模板并返回响应

def flow_details(request):
    # 业务流程详情,也是业务步骤列表
    pass
    projects = {'业务步骤1', '业务步骤2'}  # 获取所有项目
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'processes_flow_details.html',context)  # 渲染模板并返回响应

def addstep(request):
    # 业务步骤新增
    pass
    return render(request, 'processes_flow_list.html', )  # 渲染模板并返回响应

def deletestep(request):
    # 业务步骤删除
    pass
    return render(request, 'processes_deletestep.html', )  # 渲染模板并返回响应

def detailsstep(request):
    # 业务步骤详情
    projects = {'业务步骤详情1', '业务步骤详情2'}  # 获取所有接口用例
    context = {'projects': projects}  # 创建上下文数据
    return render(request, 'processes_detailsstep.html', context)  # 渲染模板并返回响应

processes/templates/processes_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>业务流程删除成功</title>
</head>
<body>
    <div >
        <a href="{% url 'processes:flow_list' %}">返回上一页</a>
        <h1>业务流程删除成功</h1>
    </div>
</body>
</html>

processes/templates/processes_deletestep.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>业务流程步骤删除成功</title>
</head>
<body>
    <div >
        <a href="{% url 'processes:flow_details' %}">返回上一页</a>
        <h1>业务流程步骤删除成功</h1>
    </div>
</body>
</html>

processes/templates/processes_detailsstep.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>业务流程步骤详情</title>
</head>
<body>
    <div >
        <a href="{% url 'processes:flow_details' %}">返回上一页</a>
        <h1>业务流程步骤详情</h1>
        {% for project in projects %}
            <div class="project">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
            </div>
        {% endfor %}
    </div>
</body>
</html>

processes/templates/processes_flow_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>业务流程步骤列表</title>
</head>
<body>
    <div >
        <a href="{% url 'processes:flow_list' %}">返回上一页</a>
        <h1>业务流程步骤列表</h1>
        <form method="post" action="{% url 'processes:flow_details' %}">
            {% csrf_token %}
            <input type="text" name="project_name" style="width: 200px; margin-right: 10px;" placeholder="请输入用例id">
            <button type="submit">新增步22骤</button>
        </form>
        {% for project in projects %}
            <div class="project">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
                <a href="{% url 'processes:detailsstep' %}">业务步骤详情</a>
                <a href="{% url 'processes:deletestep' %}">业务步骤删除</a>
            </div>
        {% endfor %}
    </div>
</body>
</html>

processes/templates/processes_flow_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>业务流程flow列表</title>
</head>
<body>
    <div >
        <a href="{% url 'project:project_details_list' %}">返回上一页</a>
        <h1>业务流程flow列表</h1>
        {% for project in projects %}
            <div class="project">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
                <a href="{% url 'processes:flow_details' %}">业务流程详情</a>
                <a href="{% url 'processes:flow_delete' %}">业务流程删除</a>
            </div>
        {% endfor %}
    </div>
</body>
</html>